### ISSUE TITLE
Support for Life A2 NC

### ISSUE THREAD

**Issue by 3lack5ky** [semvis123/Sonitus#5]
It would be great, if you could add support for the Soundcore Life A2 NC.

**Comment by semvis123** [comment]
Have you tried it anyway, because it might work even though I haven't listed it.

**Comment by 3lack5ky** [comment]
Yes, I have tried it, I selected the headphones from the menu inside the Sonitus settings. If I try to change to noise cancel, the blue button appears and then disappears without any changes. Inside the Soundcore app it’s working normally.

**Comment by semvis123** [comment]
Okay, could you message me on Discord, I communication is a bit easier over there. I will need some specific logs.

**Comment by 3lack5ky** [comment]
No problem, I will write you tomorrow on discord :)

**Comment by AleksIralda** [comment]
I have the same model, and I had try but not work, this can be great make support this model.

**Comment by semvis123** [comment]
Hi @AleksIralda , I've send you the test version over Discord. I haven't released that version yet because it doesn't automatically detect the device, I might add a setting to choose the headphones model in the preference bundle to bypass this.
