### ISSUE TITLE
Compatibility Request - Earfun Air Pro 

### ISSUE THREAD

**Issue by vasileioskorompilias** [semvis123/Sonitus#6]
Hello there!
I was looking for such an app for quite some time.

I selected my Earfun Air Pro headphones and the noise cancellation option appears, but it does not do anything.
Also, when I select the noise cancellation option (or the other ones) with the support of your addon, the option gets blue for a second and then it unselects itself, like it does not wanna keep it on.

The headphones have built in 3 modes (Normal, Ambient, and Noise Reduction) and they can be changed by tapping the earpiece 3 times. I tried changing the setting manually and chosing the ios option in each case, but no difference.
Although their noise cancellation is a bit crap. If you think you can do anything it would be awesome!!!

Thank youuuuuuuuuuuuuu!!!!!!!!!!!!! <3 <3 <3

**Comment by semvis123** [comment]
Hello, Sonitus currently has no support for the Earfun Air Pro, it could be possible to add support, but there has to be an app that can set the noise control modes (which I don't think there is for Earfun). So I don't think it is possible to add the compatibility.
